version: '3'
services:
  development:
    image: prakashjoshi/rkmasohra:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development # Set the Node.js environment to development
  production:
    image: prakashjoshi/rkmasohra:latest
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production # Set the Node.js environment to production
networks:
  external:
    driver: bridge
